name: Coverage Report

on:
  workflow_dispatch:
  push:
    branches: [ master, main ]

jobs:
  coverage:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Scala
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '18'
          cache: 'sbt'
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
            ~/.bitcoin-s/binaries
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Download binaries
        run: sbt downloadBitcoind downloadLnd downloadCLightning
      - name: Run Tests
        run: sbt clean coverage test coverageAggregate
      - name: Coverage Report
        run: sbt coverageReport
      - name: Upload coverage data to Codecov
        uses: codecov/codecov-action@v2
        with:
          fail_ci_if_error: true
